In [6]:
import numpy as np

ordem = 4

# Matriz A com valores de 1 a 100
matriz_a = np.random.randint(1, 100, (ordem, ordem))

# Matriz B com valores de 1 a 100
matriz_b = np.random.randint(1, 100, (ordem, ordem))


# Calculando o produto das matrizes
produto = np.matmul(matriz_a, matriz_b)


print("Matriz A:")
print(matriz_a)
print("\nMatriz B:")
print(matriz_b)
print("\nProduto das matrizes A e B:")
print(produto)


Matriz A:
[[60 95 51 84]
 [68 64 15 18]
 [ 8 41 32 78]
 [28 26 39 22]]

Matriz B:
[[33 24 68 90]
 [79 62 74 90]
 [82 46 40 63]
 [45 29 45  7]]

Produto das matrizes A e B:
[[17447 12112 16930 17751]
 [ 9340  6812 10770 12951]
 [ 9637  6468  8368  6972]
 [ 7166  4716  6378  7471]]
